# Generated by Django 6.0.1 on 2026-10-06 08:27

import django.db.models.deletion
import galeri.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasarim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kod', models.CharField(default=galeri.models.yeni_kod, editable=False, max_length=16, unique=True)),
                ('baslik', models.CharField(max_length=80)),
                ('aciklama', models.TextField(blank=True, max_length=500)),
                ('yazar_adi', models.CharField(blank=True, max_length=60)),
                ('plan', models.JSONField()),
                ('onizleme', models.CharField(blank=True, max_length=200)),
                ('galeride', models.BooleanField(default=True)),
                ('gizli', models.BooleanField(default=False)),
                ('anahtar_ozeti', models.CharField(max_length=64)),
                ('ip_ozeti', models.CharField(db_index=True, max_length=64)),
                ('begeni_sayisi', models.PositiveIntegerField(default=0)),
                ('kopya_sayisi', models.PositiveIntegerField(default=0)),
                ('goruntulenme', models.PositiveIntegerField(default=0)),
                ('sikayet_sayisi', models.PositiveIntegerField(default=0)),
                ('olusturma', models.DateTimeField(auto_now_add=True)),
                ('guncelleme', models.DateTimeField(auto_now=True)),
                ('kaynak', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kopyalar', to='galeri.tasarim')),
            ],
            options={
                'ordering': ['-olusturma'],
            },
        ),
        migrations.CreateModel(
            name='Sikayet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ozeti', models.CharField(max_length=64)),
                ('neden', models.CharField(blank=True, max_length=200)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tasarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sikayetler', to='galeri.tasarim')),
            ],
        ),
        migrations.CreateModel(
            name='Begeni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_ozeti', models.CharField(max_length=64)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('tasarim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='begeniler', to='galeri.tasarim')),
            ],
        ),
        migrations.AddIndex(
            model_name='tasarim',
            index=models.Index(fields=['galeride', 'gizli', '-olusturma'], name='galeri_tasa_galerid_2f1af0_idx'),
        ),
        migrations.AddIndex(
            model_name='tasarim',
            index=models.Index(fields=['galeride', 'gizli', '-begeni_sayisi'], name='galeri_tasa_galerid_650d5d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sikayet',
            constraint=models.UniqueConstraint(fields=('tasarim', 'ip_ozeti'), name='tekil_sikayet'),
        ),
        migrations.AddConstraint(
            model_name='begeni',
            constraint=models.UniqueConstraint(fields=('tasarim', 'ip_ozeti'), name='tekil_begeni'),
        ),
    ]
