# Generated by Django 6.0.1 on 2026-10-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=24, unique=True)),
            ],
            options={
                'ordering': ['ad'],
            },
        ),
        migrations.AddField(
            model_name='tasarim',
            name='etiketler',
            field=models.ManyToManyField(blank=True, related_name='tasarimlar', to='galeri.etiket'),
        ),
    ]
