# Generated by Django 6.0.1 on 2026-10-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeri', '0002_etiketler'),
    ]

    operations = [
        migrations.AddField(
            model_name='sikayet',
            name='tur',
            field=models.CharField(choices=[('uygunsuz', 'Uygunsuz içerik'), ('spam', 'Reklam / istenmeyen içerik'), ('telif', 'Başkasının tasarımı / telif'), ('kisisel', 'Kişisel bilgi içeriyor'), ('diger', 'Diğer')], default='diger', max_length=12),
        ),
    ]
